// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_wireguard {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class WireguardHostApi;
  friend class WireguardFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Tunnel runtime state. Mirrors com.wireguard.android.backend.Tunnel.State.
enum class TunnelState {
  kDown = 0,
  kToggle = 1,
  kUp = 2
};

// Identifies which underlying engine is in use.
enum class BackendKind {
  // Linux kernel WireGuard module (via wg-quick).
  kKernel = 0,
  // Userspace implementation: wireguard-go on Android, or
  // wireguard-go / boringtun on Linux (via wg-quick env var).
  kUserspace = 1,
  // Backend not initialised yet (or unavailable).
  kUnknown = 2
};


// A snapshot of a tunnel's runtime status.
//
// Generated class from Pigeon that represents data sent in messages.
class TunnelStatus {
 public:
  // Constructs an object setting all fields.
  explicit TunnelStatus(
    const std::string& name,
    const TunnelState& state,
    int64_t rx,
    int64_t tx,
    int64_t handshake);

  // Tunnel/interface name (e.g. "wg0").
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // Current state.
  const TunnelState& state() const;
  void set_state(const TunnelState& value_arg);

  // Total bytes received across all peers.
  int64_t rx() const;
  void set_rx(int64_t value_arg);

  // Total bytes transmitted across all peers.
  int64_t tx() const;
  void set_tx(int64_t value_arg);

  // Latest handshake epoch milliseconds (0 if none yet).
  int64_t handshake() const;
  void set_handshake(int64_t value_arg);

  bool operator==(const TunnelStatus& other) const;
  bool operator!=(const TunnelStatus& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static TunnelStatus FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WireguardHostApi;
  friend class WireguardFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  TunnelState state_;
  int64_t rx_;
  int64_t tx_;
  int64_t handshake_;
};


// Generated class from Pigeon that represents data sent in messages.
class BackendInfo {
 public:
  // Constructs an object setting all fields.
  explicit BackendInfo(
    const BackendKind& kind,
    const std::string& detail);

  const BackendKind& kind() const;
  void set_kind(const BackendKind& value_arg);

  // Free-form description (e.g. "GoBackend", "WgQuickBackend (kernel)",
  // "wg-quick + wireguard-go").
  const std::string& detail() const;
  void set_detail(std::string_view value_arg);

  bool operator==(const BackendInfo& other) const;
  bool operator!=(const BackendInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static BackendInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class WireguardHostApi;
  friend class WireguardFlutterApi;
  friend class PigeonInternalCodecSerializer;
  BackendKind kind_;
  std::string detail_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Host -> platform calls. All implementations must be reentrant and may be
// called from any isolate / thread.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class WireguardHostApi {
 public:
  WireguardHostApi(const WireguardHostApi&) = delete;
  WireguardHostApi& operator=(const WireguardHostApi&) = delete;
  virtual ~WireguardHostApi() {}
  // Bring the tunnel up with the given wg-quick / wg-config string.
  // Throws [PlatformException] with code "START_FAILED" on backend failure.
  virtual void Start(
    const std::string& name,
    const std::string& config,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Bring the named tunnel down. No-op if already down.
  virtual void Stop(
    const std::string& name,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Returns the current status. Throws if the tunnel was never started.
  virtual void Status(
    const std::string& name,
    std::function<void(ErrorOr<TunnelStatus> reply)> result) = 0;
  // Returns the names of all currently-known tunnels (including DOWN ones
  // that were started in this process lifetime).
  virtual void TunnelNames(std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  // Returns the active backend.
  virtual void Backend(std::function<void(ErrorOr<BackendInfo> reply)> result) = 0;

  // The codec used by WireguardHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `WireguardHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    WireguardHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    WireguardHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  WireguardHostApi() = default;
};
// Platform -> host events.
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class WireguardFlutterApi {
 public:
  WireguardFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  WireguardFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Pushed whenever a tunnel changes state or its statistics tick.
  void OnTunnelStatus(
    const TunnelStatus& status,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace flutter_wireguard
#endif  // PIGEON_MESSAGES_G_H_
