// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_wireguard {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// TunnelStatus

TunnelStatus::TunnelStatus(
  const std::string& name,
  const TunnelState& state,
  int64_t rx,
  int64_t tx,
  int64_t handshake)
 : name_(name),
    state_(state),
    rx_(rx),
    tx_(tx),
    handshake_(handshake) {}

const std::string& TunnelStatus::name() const {
  return name_;
}

void TunnelStatus::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const TunnelState& TunnelStatus::state() const {
  return state_;
}

void TunnelStatus::set_state(const TunnelState& value_arg) {
  state_ = value_arg;
}


int64_t TunnelStatus::rx() const {
  return rx_;
}

void TunnelStatus::set_rx(int64_t value_arg) {
  rx_ = value_arg;
}


int64_t TunnelStatus::tx() const {
  return tx_;
}

void TunnelStatus::set_tx(int64_t value_arg) {
  tx_ = value_arg;
}


int64_t TunnelStatus::handshake() const {
  return handshake_;
}

void TunnelStatus::set_handshake(int64_t value_arg) {
  handshake_ = value_arg;
}


EncodableList TunnelStatus::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(name_));
  list.push_back(CustomEncodableValue(state_));
  list.push_back(EncodableValue(rx_));
  list.push_back(EncodableValue(tx_));
  list.push_back(EncodableValue(handshake_));
  return list;
}

TunnelStatus TunnelStatus::FromEncodableList(const EncodableList& list) {
  TunnelStatus decoded(
    std::get<std::string>(list[0]),
    std::any_cast<const TunnelState&>(std::get<CustomEncodableValue>(list[1])),
    std::get<int64_t>(list[2]),
    std::get<int64_t>(list[3]),
    std::get<int64_t>(list[4]));
  return decoded;
}

// BackendInfo

BackendInfo::BackendInfo(
  const BackendKind& kind,
  const std::string& detail)
 : kind_(kind),
    detail_(detail) {}

const BackendKind& BackendInfo::kind() const {
  return kind_;
}

void BackendInfo::set_kind(const BackendKind& value_arg) {
  kind_ = value_arg;
}


const std::string& BackendInfo::detail() const {
  return detail_;
}

void BackendInfo::set_detail(std::string_view value_arg) {
  detail_ = value_arg;
}


EncodableList BackendInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(CustomEncodableValue(kind_));
  list.push_back(EncodableValue(detail_));
  return list;
}

BackendInfo BackendInfo::FromEncodableList(const EncodableList& list) {
  BackendInfo decoded(
    std::any_cast<const BackendKind&>(std::get<CustomEncodableValue>(list[0])),
    std::get<std::string>(list[1]));
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<TunnelState>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<BackendKind>(enum_arg_value));
      }
    case 131: {
        return CustomEncodableValue(TunnelStatus::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(BackendInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(TunnelState)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<TunnelState>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(BackendKind)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<BackendKind>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(TunnelStatus)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<TunnelStatus>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(BackendInfo)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<BackendInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by WireguardHostApi.
const flutter::StandardMessageCodec& WireguardHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `WireguardHostApi` to handle messages through the `binary_messenger`.
void WireguardHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  WireguardHostApi* api) {
  WireguardHostApi::SetUp(binary_messenger, api, "");
}

void WireguardHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  WireguardHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.start" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_name_arg = args.at(0);
          if (encodable_name_arg.IsNull()) {
            reply(WrapError("name_arg unexpectedly null."));
            return;
          }
          const auto& name_arg = std::get<std::string>(encodable_name_arg);
          const auto& encodable_config_arg = args.at(1);
          if (encodable_config_arg.IsNull()) {
            reply(WrapError("config_arg unexpectedly null."));
            return;
          }
          const auto& config_arg = std::get<std::string>(encodable_config_arg);
          api->Start(name_arg, config_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.stop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_name_arg = args.at(0);
          if (encodable_name_arg.IsNull()) {
            reply(WrapError("name_arg unexpectedly null."));
            return;
          }
          const auto& name_arg = std::get<std::string>(encodable_name_arg);
          api->Stop(name_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.status" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_name_arg = args.at(0);
          if (encodable_name_arg.IsNull()) {
            reply(WrapError("name_arg unexpectedly null."));
            return;
          }
          const auto& name_arg = std::get<std::string>(encodable_name_arg);
          api->Status(name_arg, [reply](ErrorOr<TunnelStatus>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.tunnelNames" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->TunnelNames([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.backend" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->Backend([reply](ErrorOr<BackendInfo>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue WireguardHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue WireguardHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
WireguardFlutterApi::WireguardFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

WireguardFlutterApi::WireguardFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& WireguardFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void WireguardFlutterApi::OnTunnelStatus(
  const TunnelStatus& status_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(status_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace flutter_wireguard
