name: flutter_wireguard
description: A Flutter plugin for managing WireGuard VPN tunnels. Currently supports Android, with iOS, macOS, Linux, and Windows in progress.
version: 0.0.1
homepage: https://github.com/pedramktb/flutter-wireguard

environment:
  sdk: ^3.1.0
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: com.pedramktb.flutter_wireguard
        pluginClass: FlutterWireguardPlugin
      ios:
        pluginClass: FlutterWireguardPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterWireguardPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: FlutterWireguardPlugin
      windows:
        pluginClass: FlutterWireguardPluginCApi
