name: flutter_wireguard
description: A Flutter plugin for managing WireGuard VPN tunnels. Supports Android, Linux and Windows; iOS and macOS are work-in-progress.
version: 0.2.0
homepage: https://github.com/pedramktb/flutter-wireguard

environment:
  sdk: ^3.4.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.pedramktb.flutter_wireguard
        pluginClass: FlutterWireguardPlugin
      linux:
        pluginClass: FlutterWireguardPlugin
      ios:
        pluginClass: FlutterWireguardPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterWireguardPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: FlutterWireguardPluginCApi
