// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.pedramktb.flutter_wireguard

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Tunnel runtime state. Mirrors com.wireguard.android.backend.Tunnel.State. */
enum class TunnelState(val raw: Int) {
  DOWN(0),
  TOGGLE(1),
  UP(2);

  companion object {
    fun ofRaw(raw: Int): TunnelState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Identifies which underlying engine is in use. */
enum class BackendKind(val raw: Int) {
  /** Linux kernel WireGuard module (via wg-quick). */
  KERNEL(0),
  /**
   * Userspace implementation: wireguard-go on Android, or
   * wireguard-go / boringtun on Linux (via wg-quick env var).
   */
  USERSPACE(1),
  /** Backend not initialised yet (or unavailable). */
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): BackendKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A snapshot of a tunnel's runtime status.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TunnelStatus (
  /** Tunnel/interface name (e.g. "wg0"). */
  val name: String,
  /** Current state. */
  val state: TunnelState,
  /** Total bytes received across all peers. */
  val rx: Long,
  /** Total bytes transmitted across all peers. */
  val tx: Long,
  /** Latest handshake epoch milliseconds (0 if none yet). */
  val handshake: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TunnelStatus {
      val name = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as TunnelState
      val rx = pigeonVar_list[2] as Long
      val tx = pigeonVar_list[3] as Long
      val handshake = pigeonVar_list[4] as Long
      return TunnelStatus(name, state, rx, tx, handshake)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      state,
      rx,
      tx,
      handshake,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BackendInfo (
  val kind: BackendKind,
  /**
   * Free-form description (e.g. "GoBackend", "WgQuickBackend (kernel)",
   * "wg-quick + wireguard-go").
   */
  val detail: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackendInfo {
      val kind = pigeonVar_list[0] as BackendKind
      val detail = pigeonVar_list[1] as String
      return BackendInfo(kind, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      detail,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TunnelState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BackendKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TunnelStatus.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackendInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TunnelState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is BackendKind -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is TunnelStatus -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BackendInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host -> platform calls. All implementations must be reentrant and may be
 * called from any isolate / thread.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WireguardHostApi {
  /**
   * Bring the tunnel up with the given wg-quick / wg-config string.
   * Throws [PlatformException] with code "START_FAILED" on backend failure.
   */
  fun start(name: String, config: String, callback: (Result<Unit>) -> Unit)
  /** Bring the named tunnel down. No-op if already down. */
  fun stop(name: String, callback: (Result<Unit>) -> Unit)
  /** Returns the current status. Throws if the tunnel was never started. */
  fun status(name: String, callback: (Result<TunnelStatus>) -> Unit)
  /**
   * Returns the names of all currently-known tunnels (including DOWN ones
   * that were started in this process lifetime).
   */
  fun tunnelNames(callback: (Result<List<String>>) -> Unit)
  /** Returns the active backend. */
  fun backend(callback: (Result<BackendInfo>) -> Unit)

  companion object {
    /** The codec used by WireguardHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `WireguardHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WireguardHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val configArg = args[1] as String
            api.start(nameArg, configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            api.stop(nameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            api.status(nameArg) { result: Result<TunnelStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.tunnelNames$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.tunnelNames{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.backend$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.backend{ result: Result<BackendInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Platform -> host events.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class WireguardFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WireguardFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Pushed whenever a tunnel changes state or its statistics tick. */
  fun onTunnelStatus(statusArg: TunnelStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
