// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Tunnel runtime state. Mirrors com.wireguard.android.backend.Tunnel.State.
enum TunnelState {
  down,
  toggle,
  up,
}

/// Identifies which underlying engine is in use.
enum BackendKind {
  /// Linux kernel WireGuard module (via wg-quick).
  kernel,
  /// Userspace implementation: wireguard-go on Android, or
  /// wireguard-go / boringtun on Linux (via wg-quick env var).
  userspace,
  /// Backend not initialised yet (or unavailable).
  unknown,
}

/// A snapshot of a tunnel's runtime status.
class TunnelStatus {
  TunnelStatus({
    required this.name,
    required this.state,
    required this.rx,
    required this.tx,
    required this.handshake,
  });

  /// Tunnel/interface name (e.g. "wg0").
  String name;

  /// Current state.
  TunnelState state;

  /// Total bytes received across all peers.
  int rx;

  /// Total bytes transmitted across all peers.
  int tx;

  /// Latest handshake epoch milliseconds (0 if none yet).
  int handshake;

  List<Object?> _toList() {
    return <Object?>[
      name,
      state,
      rx,
      tx,
      handshake,
    ];
  }

  Object encode() {
    return _toList();  }

  static TunnelStatus decode(Object result) {
    result as List<Object?>;
    return TunnelStatus(
      name: result[0]! as String,
      state: result[1]! as TunnelState,
      rx: result[2]! as int,
      tx: result[3]! as int,
      handshake: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TunnelStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(state, other.state) && _deepEquals(rx, other.rx) && _deepEquals(tx, other.tx) && _deepEquals(handshake, other.handshake);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BackendInfo {
  BackendInfo({
    required this.kind,
    required this.detail,
  });

  BackendKind kind;

  /// Free-form description (e.g. "GoBackend", "WgQuickBackend (kernel)",
  /// "wg-quick + wireguard-go").
  String detail;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      detail,
    ];
  }

  Object encode() {
    return _toList();  }

  static BackendInfo decode(Object result) {
    result as List<Object?>;
    return BackendInfo(
      kind: result[0]! as BackendKind,
      detail: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BackendInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TunnelState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BackendKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is TunnelStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is BackendInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : TunnelState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : BackendKind.values[value];
      case 131:
        return TunnelStatus.decode(readValue(buffer)!);
      case 132:
        return BackendInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host -> platform calls. All implementations must be reentrant and may be
/// called from any isolate / thread.
class WireguardHostApi {
  /// Constructor for [WireguardHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WireguardHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Bring the tunnel up with the given wg-quick / wg-config string.
  /// Throws [PlatformException] with code "START_FAILED" on backend failure.
  Future<void> start(String name, String config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name, config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Bring the named tunnel down. No-op if already down.
  Future<void> stop(String name) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns the current status. Throws if the tunnel was never started.
  Future<TunnelStatus> status(String name) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as TunnelStatus;
  }

  /// Returns the names of all currently-known tunnels (including DOWN ones
  /// that were started in this process lifetime).
  Future<List<String>> tunnelNames() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.tunnelNames$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Returns the active backend.
  Future<BackendInfo> backend() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.backend$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BackendInfo;
  }
}

/// Platform -> host events.
abstract class WireguardFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Pushed whenever a tunnel changes state or its statistics tick.
  void onTunnelStatus(TunnelStatus status);

  static void setUp(WireguardFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final TunnelStatus arg_status = args[0]! as TunnelStatus;
          try {
            api.onTunnelStatus(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
