// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Tunnel runtime state. Mirrors com.wireguard.android.backend.Tunnel.State.
enum TunnelState {
  down,
  toggle,
  up,
}

/// Identifies which underlying engine is in use.
enum BackendKind {
  /// Linux kernel WireGuard module (via wg-quick).
  kernel,
  /// Userspace implementation: wireguard-go on Android, or
  /// wireguard-go / boringtun on Linux (via wg-quick env var).
  userspace,
  /// Backend not initialised yet (or unavailable).
  unknown,
}

/// A snapshot of a tunnel's runtime status.
class TunnelStatus {
  TunnelStatus({
    required this.name,
    required this.state,
    required this.rx,
    required this.tx,
    required this.handshake,
  });

  /// Tunnel/interface name (e.g. "wg0").
  String name;

  /// Current state.
  TunnelState state;

  /// Total bytes received across all peers.
  int rx;

  /// Total bytes transmitted across all peers.
  int tx;

  /// Latest handshake epoch milliseconds (0 if none yet).
  int handshake;

  Object encode() {
    return <Object?>[
      name,
      state,
      rx,
      tx,
      handshake,
    ];
  }

  static TunnelStatus decode(Object result) {
    result as List<Object?>;
    return TunnelStatus(
      name: result[0]! as String,
      state: result[1]! as TunnelState,
      rx: result[2]! as int,
      tx: result[3]! as int,
      handshake: result[4]! as int,
    );
  }
}

class BackendInfo {
  BackendInfo({
    required this.kind,
    required this.detail,
  });

  BackendKind kind;

  /// Free-form description (e.g. "GoBackend", "WgQuickBackend (kernel)",
  /// "wg-quick + wireguard-go").
  String detail;

  Object encode() {
    return <Object?>[
      kind,
      detail,
    ];
  }

  static BackendInfo decode(Object result) {
    result as List<Object?>;
    return BackendInfo(
      kind: result[0]! as BackendKind,
      detail: result[1]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TunnelState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BackendKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is TunnelStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is BackendInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TunnelState.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BackendKind.values[value];
      case 131: 
        return TunnelStatus.decode(readValue(buffer)!);
      case 132: 
        return BackendInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host -> platform calls. All implementations must be reentrant and may be
/// called from any isolate / thread.
class WireguardHostApi {
  /// Constructor for [WireguardHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WireguardHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Bring the tunnel up with the given wg-quick / wg-config string.
  /// Throws [PlatformException] with code "START_FAILED" on backend failure.
  Future<void> start(String name, String config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name, config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Bring the named tunnel down. No-op if already down.
  Future<void> stop(String name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns the current status. Throws if the tunnel was never started.
  Future<TunnelStatus> status(String name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.status$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as TunnelStatus?)!;
    }
  }

  /// Returns the names of all currently-known tunnels (including DOWN ones
  /// that were started in this process lifetime).
  Future<List<String>> tunnelNames() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.tunnelNames$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }

  /// Returns the active backend.
  Future<BackendInfo> backend() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.backend$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BackendInfo?)!;
    }
  }
}

/// Platform -> host events.
abstract class WireguardFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Pushed whenever a tunnel changes state or its statistics tick.
  void onTunnelStatus(TunnelStatus status);

  static void setUp(WireguardFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TunnelStatus? arg_status = (args[0] as TunnelStatus?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus was null, expected non-null TunnelStatus.');
          try {
            api.onTunnelStatus(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
