// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "messages.g.h"

struct _FlutterWireguardTunnelStatus {
  GObject parent_instance;

  gchar* name;
  FlutterWireguardTunnelState state;
  int64_t rx;
  int64_t tx;
  int64_t handshake;
};

G_DEFINE_TYPE(FlutterWireguardTunnelStatus, flutter_wireguard_tunnel_status, G_TYPE_OBJECT)

static void flutter_wireguard_tunnel_status_dispose(GObject* object) {
  FlutterWireguardTunnelStatus* self = FLUTTER_WIREGUARD_TUNNEL_STATUS(object);
  g_clear_pointer(&self->name, g_free);
  G_OBJECT_CLASS(flutter_wireguard_tunnel_status_parent_class)->dispose(object);
}

static void flutter_wireguard_tunnel_status_init(FlutterWireguardTunnelStatus* self) {
}

static void flutter_wireguard_tunnel_status_class_init(FlutterWireguardTunnelStatusClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_tunnel_status_dispose;
}

FlutterWireguardTunnelStatus* flutter_wireguard_tunnel_status_new(const gchar* name, FlutterWireguardTunnelState state, int64_t rx, int64_t tx, int64_t handshake) {
  FlutterWireguardTunnelStatus* self = FLUTTER_WIREGUARD_TUNNEL_STATUS(g_object_new(flutter_wireguard_tunnel_status_get_type(), nullptr));
  self->name = g_strdup(name);
  self->state = state;
  self->rx = rx;
  self->tx = tx;
  self->handshake = handshake;
  return self;
}

const gchar* flutter_wireguard_tunnel_status_get_name(FlutterWireguardTunnelStatus* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_TUNNEL_STATUS(self), nullptr);
  return self->name;
}

FlutterWireguardTunnelState flutter_wireguard_tunnel_status_get_state(FlutterWireguardTunnelStatus* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_TUNNEL_STATUS(self), static_cast<FlutterWireguardTunnelState>(0));
  return self->state;
}

int64_t flutter_wireguard_tunnel_status_get_rx(FlutterWireguardTunnelStatus* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_TUNNEL_STATUS(self), 0);
  return self->rx;
}

int64_t flutter_wireguard_tunnel_status_get_tx(FlutterWireguardTunnelStatus* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_TUNNEL_STATUS(self), 0);
  return self->tx;
}

int64_t flutter_wireguard_tunnel_status_get_handshake(FlutterWireguardTunnelStatus* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_TUNNEL_STATUS(self), 0);
  return self->handshake;
}

static FlValue* flutter_wireguard_tunnel_status_to_list(FlutterWireguardTunnelStatus* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->name));
  fl_value_append_take(values, fl_value_new_custom(129, fl_value_new_int(self->state), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_int(self->rx));
  fl_value_append_take(values, fl_value_new_int(self->tx));
  fl_value_append_take(values, fl_value_new_int(self->handshake));
  return values;
}

static FlutterWireguardTunnelStatus* flutter_wireguard_tunnel_status_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* name = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  FlutterWireguardTunnelState state = static_cast<FlutterWireguardTunnelState>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value1)))));
  FlValue* value2 = fl_value_get_list_value(values, 2);
  int64_t rx = fl_value_get_int(value2);
  FlValue* value3 = fl_value_get_list_value(values, 3);
  int64_t tx = fl_value_get_int(value3);
  FlValue* value4 = fl_value_get_list_value(values, 4);
  int64_t handshake = fl_value_get_int(value4);
  return flutter_wireguard_tunnel_status_new(name, state, rx, tx, handshake);
}

struct _FlutterWireguardBackendInfo {
  GObject parent_instance;

  FlutterWireguardBackendKind kind;
  gchar* detail;
};

G_DEFINE_TYPE(FlutterWireguardBackendInfo, flutter_wireguard_backend_info, G_TYPE_OBJECT)

static void flutter_wireguard_backend_info_dispose(GObject* object) {
  FlutterWireguardBackendInfo* self = FLUTTER_WIREGUARD_BACKEND_INFO(object);
  g_clear_pointer(&self->detail, g_free);
  G_OBJECT_CLASS(flutter_wireguard_backend_info_parent_class)->dispose(object);
}

static void flutter_wireguard_backend_info_init(FlutterWireguardBackendInfo* self) {
}

static void flutter_wireguard_backend_info_class_init(FlutterWireguardBackendInfoClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_backend_info_dispose;
}

FlutterWireguardBackendInfo* flutter_wireguard_backend_info_new(FlutterWireguardBackendKind kind, const gchar* detail) {
  FlutterWireguardBackendInfo* self = FLUTTER_WIREGUARD_BACKEND_INFO(g_object_new(flutter_wireguard_backend_info_get_type(), nullptr));
  self->kind = kind;
  self->detail = g_strdup(detail);
  return self;
}

FlutterWireguardBackendKind flutter_wireguard_backend_info_get_kind(FlutterWireguardBackendInfo* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_BACKEND_INFO(self), static_cast<FlutterWireguardBackendKind>(0));
  return self->kind;
}

const gchar* flutter_wireguard_backend_info_get_detail(FlutterWireguardBackendInfo* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_BACKEND_INFO(self), nullptr);
  return self->detail;
}

static FlValue* flutter_wireguard_backend_info_to_list(FlutterWireguardBackendInfo* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_custom(130, fl_value_new_int(self->kind), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_string(self->detail));
  return values;
}

static FlutterWireguardBackendInfo* flutter_wireguard_backend_info_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  FlutterWireguardBackendKind kind = static_cast<FlutterWireguardBackendKind>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* detail = fl_value_get_string(value1);
  return flutter_wireguard_backend_info_new(kind, detail);
}

struct _FlutterWireguardMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(FlutterWireguardMessageCodec, flutter_wireguard_message_codec, fl_standard_message_codec_get_type())

static gboolean flutter_wireguard_message_codec_write_flutter_wireguard_tunnel_state(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 129;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean flutter_wireguard_message_codec_write_flutter_wireguard_backend_kind(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = 130;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean flutter_wireguard_message_codec_write_flutter_wireguard_tunnel_status(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterWireguardTunnelStatus* value, GError** error) {
  uint8_t type = 131;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_wireguard_tunnel_status_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_wireguard_message_codec_write_flutter_wireguard_backend_info(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterWireguardBackendInfo* value, GError** error) {
  uint8_t type = 132;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_wireguard_backend_info_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_wireguard_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case 129:
        return flutter_wireguard_message_codec_write_flutter_wireguard_tunnel_state(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 130:
        return flutter_wireguard_message_codec_write_flutter_wireguard_backend_kind(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case 131:
        return flutter_wireguard_message_codec_write_flutter_wireguard_tunnel_status(codec, buffer, FLUTTER_WIREGUARD_TUNNEL_STATUS(fl_value_get_custom_value_object(value)), error);
      case 132:
        return flutter_wireguard_message_codec_write_flutter_wireguard_backend_info(codec, buffer, FLUTTER_WIREGUARD_BACKEND_INFO(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(flutter_wireguard_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* flutter_wireguard_message_codec_read_flutter_wireguard_tunnel_state(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(129, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* flutter_wireguard_message_codec_read_flutter_wireguard_backend_kind(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(130, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* flutter_wireguard_message_codec_read_flutter_wireguard_tunnel_status(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterWireguardTunnelStatus) value = flutter_wireguard_tunnel_status_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(131, G_OBJECT(value));
}

static FlValue* flutter_wireguard_message_codec_read_flutter_wireguard_backend_info(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterWireguardBackendInfo) value = flutter_wireguard_backend_info_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(132, G_OBJECT(value));
}

static FlValue* flutter_wireguard_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case 129:
      return flutter_wireguard_message_codec_read_flutter_wireguard_tunnel_state(codec, buffer, offset, error);
    case 130:
      return flutter_wireguard_message_codec_read_flutter_wireguard_backend_kind(codec, buffer, offset, error);
    case 131:
      return flutter_wireguard_message_codec_read_flutter_wireguard_tunnel_status(codec, buffer, offset, error);
    case 132:
      return flutter_wireguard_message_codec_read_flutter_wireguard_backend_info(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(flutter_wireguard_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void flutter_wireguard_message_codec_init(FlutterWireguardMessageCodec* self) {
}

static void flutter_wireguard_message_codec_class_init(FlutterWireguardMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = flutter_wireguard_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = flutter_wireguard_message_codec_read_value_of_type;
}

static FlutterWireguardMessageCodec* flutter_wireguard_message_codec_new() {
  FlutterWireguardMessageCodec* self = FLUTTER_WIREGUARD_MESSAGE_CODEC(g_object_new(flutter_wireguard_message_codec_get_type(), nullptr));
  return self;
}

struct _FlutterWireguardWireguardHostApiResponseHandle {
  GObject parent_instance;

  FlBasicMessageChannel* channel;
  FlBasicMessageChannelResponseHandle* response_handle;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApiResponseHandle, flutter_wireguard_wireguard_host_api_response_handle, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_response_handle_dispose(GObject* object) {
  FlutterWireguardWireguardHostApiResponseHandle* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_RESPONSE_HANDLE(object);
  g_clear_object(&self->channel);
  g_clear_object(&self->response_handle);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_response_handle_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_response_handle_init(FlutterWireguardWireguardHostApiResponseHandle* self) {
}

static void flutter_wireguard_wireguard_host_api_response_handle_class_init(FlutterWireguardWireguardHostApiResponseHandleClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_response_handle_dispose;
}

static FlutterWireguardWireguardHostApiResponseHandle* flutter_wireguard_wireguard_host_api_response_handle_new(FlBasicMessageChannel* channel, FlBasicMessageChannelResponseHandle* response_handle) {
  FlutterWireguardWireguardHostApiResponseHandle* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_RESPONSE_HANDLE(g_object_new(flutter_wireguard_wireguard_host_api_response_handle_get_type(), nullptr));
  self->channel = FL_BASIC_MESSAGE_CHANNEL(g_object_ref(channel));
  self->response_handle = FL_BASIC_MESSAGE_CHANNEL_RESPONSE_HANDLE(g_object_ref(response_handle));
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApiStartResponse, flutter_wireguard_wireguard_host_api_start_response, FLUTTER_WIREGUARD, WIREGUARD_HOST_API_START_RESPONSE, GObject)

struct _FlutterWireguardWireguardHostApiStartResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApiStartResponse, flutter_wireguard_wireguard_host_api_start_response, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_start_response_dispose(GObject* object) {
  FlutterWireguardWireguardHostApiStartResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_START_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_start_response_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_start_response_init(FlutterWireguardWireguardHostApiStartResponse* self) {
}

static void flutter_wireguard_wireguard_host_api_start_response_class_init(FlutterWireguardWireguardHostApiStartResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_start_response_dispose;
}

static FlutterWireguardWireguardHostApiStartResponse* flutter_wireguard_wireguard_host_api_start_response_new() {
  FlutterWireguardWireguardHostApiStartResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_START_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_start_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

static FlutterWireguardWireguardHostApiStartResponse* flutter_wireguard_wireguard_host_api_start_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterWireguardWireguardHostApiStartResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_START_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_start_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApiStopResponse, flutter_wireguard_wireguard_host_api_stop_response, FLUTTER_WIREGUARD, WIREGUARD_HOST_API_STOP_RESPONSE, GObject)

struct _FlutterWireguardWireguardHostApiStopResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApiStopResponse, flutter_wireguard_wireguard_host_api_stop_response, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_stop_response_dispose(GObject* object) {
  FlutterWireguardWireguardHostApiStopResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_STOP_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_stop_response_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_stop_response_init(FlutterWireguardWireguardHostApiStopResponse* self) {
}

static void flutter_wireguard_wireguard_host_api_stop_response_class_init(FlutterWireguardWireguardHostApiStopResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_stop_response_dispose;
}

static FlutterWireguardWireguardHostApiStopResponse* flutter_wireguard_wireguard_host_api_stop_response_new() {
  FlutterWireguardWireguardHostApiStopResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_STOP_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_stop_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

static FlutterWireguardWireguardHostApiStopResponse* flutter_wireguard_wireguard_host_api_stop_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterWireguardWireguardHostApiStopResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_STOP_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_stop_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApiStatusResponse, flutter_wireguard_wireguard_host_api_status_response, FLUTTER_WIREGUARD, WIREGUARD_HOST_API_STATUS_RESPONSE, GObject)

struct _FlutterWireguardWireguardHostApiStatusResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApiStatusResponse, flutter_wireguard_wireguard_host_api_status_response, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_status_response_dispose(GObject* object) {
  FlutterWireguardWireguardHostApiStatusResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_STATUS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_status_response_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_status_response_init(FlutterWireguardWireguardHostApiStatusResponse* self) {
}

static void flutter_wireguard_wireguard_host_api_status_response_class_init(FlutterWireguardWireguardHostApiStatusResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_status_response_dispose;
}

static FlutterWireguardWireguardHostApiStatusResponse* flutter_wireguard_wireguard_host_api_status_response_new(FlutterWireguardTunnelStatus* return_value) {
  FlutterWireguardWireguardHostApiStatusResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_STATUS_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_status_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom_object(131, G_OBJECT(return_value)));
  return self;
}

static FlutterWireguardWireguardHostApiStatusResponse* flutter_wireguard_wireguard_host_api_status_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterWireguardWireguardHostApiStatusResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_STATUS_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_status_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApiTunnelNamesResponse, flutter_wireguard_wireguard_host_api_tunnel_names_response, FLUTTER_WIREGUARD, WIREGUARD_HOST_API_TUNNEL_NAMES_RESPONSE, GObject)

struct _FlutterWireguardWireguardHostApiTunnelNamesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApiTunnelNamesResponse, flutter_wireguard_wireguard_host_api_tunnel_names_response, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_tunnel_names_response_dispose(GObject* object) {
  FlutterWireguardWireguardHostApiTunnelNamesResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_TUNNEL_NAMES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_tunnel_names_response_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_tunnel_names_response_init(FlutterWireguardWireguardHostApiTunnelNamesResponse* self) {
}

static void flutter_wireguard_wireguard_host_api_tunnel_names_response_class_init(FlutterWireguardWireguardHostApiTunnelNamesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_tunnel_names_response_dispose;
}

static FlutterWireguardWireguardHostApiTunnelNamesResponse* flutter_wireguard_wireguard_host_api_tunnel_names_response_new(FlValue* return_value) {
  FlutterWireguardWireguardHostApiTunnelNamesResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_TUNNEL_NAMES_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_tunnel_names_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

static FlutterWireguardWireguardHostApiTunnelNamesResponse* flutter_wireguard_wireguard_host_api_tunnel_names_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterWireguardWireguardHostApiTunnelNamesResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_TUNNEL_NAMES_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_tunnel_names_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApiBackendResponse, flutter_wireguard_wireguard_host_api_backend_response, FLUTTER_WIREGUARD, WIREGUARD_HOST_API_BACKEND_RESPONSE, GObject)

struct _FlutterWireguardWireguardHostApiBackendResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApiBackendResponse, flutter_wireguard_wireguard_host_api_backend_response, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_backend_response_dispose(GObject* object) {
  FlutterWireguardWireguardHostApiBackendResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_BACKEND_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_backend_response_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_backend_response_init(FlutterWireguardWireguardHostApiBackendResponse* self) {
}

static void flutter_wireguard_wireguard_host_api_backend_response_class_init(FlutterWireguardWireguardHostApiBackendResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_backend_response_dispose;
}

static FlutterWireguardWireguardHostApiBackendResponse* flutter_wireguard_wireguard_host_api_backend_response_new(FlutterWireguardBackendInfo* return_value) {
  FlutterWireguardWireguardHostApiBackendResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_BACKEND_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_backend_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom_object(132, G_OBJECT(return_value)));
  return self;
}

static FlutterWireguardWireguardHostApiBackendResponse* flutter_wireguard_wireguard_host_api_backend_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterWireguardWireguardHostApiBackendResponse* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API_BACKEND_RESPONSE(g_object_new(flutter_wireguard_wireguard_host_api_backend_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FlutterWireguardWireguardHostApi {
  GObject parent_instance;

  const FlutterWireguardWireguardHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(FlutterWireguardWireguardHostApi, flutter_wireguard_wireguard_host_api, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_host_api_dispose(GObject* object) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(flutter_wireguard_wireguard_host_api_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_host_api_init(FlutterWireguardWireguardHostApi* self) {
}

static void flutter_wireguard_wireguard_host_api_class_init(FlutterWireguardWireguardHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_host_api_dispose;
}

static FlutterWireguardWireguardHostApi* flutter_wireguard_wireguard_host_api_new(const FlutterWireguardWireguardHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(g_object_new(flutter_wireguard_wireguard_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void flutter_wireguard_wireguard_host_api_start_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->start == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* name = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  const gchar* config = fl_value_get_string(value1);
  g_autoptr(FlutterWireguardWireguardHostApiResponseHandle) handle = flutter_wireguard_wireguard_host_api_response_handle_new(channel, response_handle);
  self->vtable->start(name, config, handle, self->user_data);
}

static void flutter_wireguard_wireguard_host_api_stop_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->stop == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* name = fl_value_get_string(value0);
  g_autoptr(FlutterWireguardWireguardHostApiResponseHandle) handle = flutter_wireguard_wireguard_host_api_response_handle_new(channel, response_handle);
  self->vtable->stop(name, handle, self->user_data);
}

static void flutter_wireguard_wireguard_host_api_status_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->status == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* name = fl_value_get_string(value0);
  g_autoptr(FlutterWireguardWireguardHostApiResponseHandle) handle = flutter_wireguard_wireguard_host_api_response_handle_new(channel, response_handle);
  self->vtable->status(name, handle, self->user_data);
}

static void flutter_wireguard_wireguard_host_api_tunnel_names_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->tunnel_names == nullptr) {
    return;
  }

  g_autoptr(FlutterWireguardWireguardHostApiResponseHandle) handle = flutter_wireguard_wireguard_host_api_response_handle_new(channel, response_handle);
  self->vtable->tunnel_names(handle, self->user_data);
}

static void flutter_wireguard_wireguard_host_api_backend_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterWireguardWireguardHostApi* self = FLUTTER_WIREGUARD_WIREGUARD_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->backend == nullptr) {
    return;
  }

  g_autoptr(FlutterWireguardWireguardHostApiResponseHandle) handle = flutter_wireguard_wireguard_host_api_response_handle_new(channel, response_handle);
  self->vtable->backend(handle, self->user_data);
}

void flutter_wireguard_wireguard_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterWireguardWireguardHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(FlutterWireguardWireguardHostApi) api_data = flutter_wireguard_wireguard_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(FlutterWireguardMessageCodec) codec = flutter_wireguard_message_codec_new();
  g_autofree gchar* start_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.start%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_channel = fl_basic_message_channel_new(messenger, start_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_channel, flutter_wireguard_wireguard_host_api_start_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* stop_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.stop%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_channel = fl_basic_message_channel_new(messenger, stop_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_channel, flutter_wireguard_wireguard_host_api_stop_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* status_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.status%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) status_channel = fl_basic_message_channel_new(messenger, status_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(status_channel, flutter_wireguard_wireguard_host_api_status_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* tunnel_names_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.tunnelNames%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) tunnel_names_channel = fl_basic_message_channel_new(messenger, tunnel_names_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(tunnel_names_channel, flutter_wireguard_wireguard_host_api_tunnel_names_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* backend_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.backend%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) backend_channel = fl_basic_message_channel_new(messenger, backend_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(backend_channel, flutter_wireguard_wireguard_host_api_backend_cb, g_object_ref(api_data), g_object_unref);
}

void flutter_wireguard_wireguard_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(FlutterWireguardMessageCodec) codec = flutter_wireguard_message_codec_new();
  g_autofree gchar* start_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.start%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_channel = fl_basic_message_channel_new(messenger, start_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* stop_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.stop%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) stop_channel = fl_basic_message_channel_new(messenger, stop_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(stop_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* status_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.status%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) status_channel = fl_basic_message_channel_new(messenger, status_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(status_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* tunnel_names_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.tunnelNames%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) tunnel_names_channel = fl_basic_message_channel_new(messenger, tunnel_names_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(tunnel_names_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* backend_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardHostApi.backend%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) backend_channel = fl_basic_message_channel_new(messenger, backend_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(backend_channel, nullptr, nullptr, nullptr);
}

void flutter_wireguard_wireguard_host_api_respond_start(FlutterWireguardWireguardHostApiResponseHandle* response_handle) {
  g_autoptr(FlutterWireguardWireguardHostApiStartResponse) response = flutter_wireguard_wireguard_host_api_start_response_new();
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "start", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_error_start(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterWireguardWireguardHostApiStartResponse) response = flutter_wireguard_wireguard_host_api_start_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "start", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_stop(FlutterWireguardWireguardHostApiResponseHandle* response_handle) {
  g_autoptr(FlutterWireguardWireguardHostApiStopResponse) response = flutter_wireguard_wireguard_host_api_stop_response_new();
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "stop", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_error_stop(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterWireguardWireguardHostApiStopResponse) response = flutter_wireguard_wireguard_host_api_stop_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "stop", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_status(FlutterWireguardWireguardHostApiResponseHandle* response_handle, FlutterWireguardTunnelStatus* return_value) {
  g_autoptr(FlutterWireguardWireguardHostApiStatusResponse) response = flutter_wireguard_wireguard_host_api_status_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "status", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_error_status(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterWireguardWireguardHostApiStatusResponse) response = flutter_wireguard_wireguard_host_api_status_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "status", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_tunnel_names(FlutterWireguardWireguardHostApiResponseHandle* response_handle, FlValue* return_value) {
  g_autoptr(FlutterWireguardWireguardHostApiTunnelNamesResponse) response = flutter_wireguard_wireguard_host_api_tunnel_names_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "tunnelNames", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_error_tunnel_names(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterWireguardWireguardHostApiTunnelNamesResponse) response = flutter_wireguard_wireguard_host_api_tunnel_names_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "tunnelNames", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_backend(FlutterWireguardWireguardHostApiResponseHandle* response_handle, FlutterWireguardBackendInfo* return_value) {
  g_autoptr(FlutterWireguardWireguardHostApiBackendResponse) response = flutter_wireguard_wireguard_host_api_backend_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "backend", error->message);
  }
}

void flutter_wireguard_wireguard_host_api_respond_error_backend(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterWireguardWireguardHostApiBackendResponse) response = flutter_wireguard_wireguard_host_api_backend_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "WireguardHostApi", "backend", error->message);
  }
}

struct _FlutterWireguardWireguardFlutterApi {
  GObject parent_instance;

  FlBinaryMessenger* messenger;
  gchar *suffix;
};

G_DEFINE_TYPE(FlutterWireguardWireguardFlutterApi, flutter_wireguard_wireguard_flutter_api, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_flutter_api_dispose(GObject* object) {
  FlutterWireguardWireguardFlutterApi* self = FLUTTER_WIREGUARD_WIREGUARD_FLUTTER_API(object);
  g_clear_object(&self->messenger);
  g_clear_pointer(&self->suffix, g_free);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_flutter_api_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_flutter_api_init(FlutterWireguardWireguardFlutterApi* self) {
}

static void flutter_wireguard_wireguard_flutter_api_class_init(FlutterWireguardWireguardFlutterApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_flutter_api_dispose;
}

FlutterWireguardWireguardFlutterApi* flutter_wireguard_wireguard_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix) {
  FlutterWireguardWireguardFlutterApi* self = FLUTTER_WIREGUARD_WIREGUARD_FLUTTER_API(g_object_new(flutter_wireguard_wireguard_flutter_api_get_type(), nullptr));
  self->messenger = FL_BINARY_MESSENGER(g_object_ref(messenger));
  self->suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  return self;
}

struct _FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse, flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response, G_TYPE_OBJECT)

static void flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_dispose(GObject* object) {
  FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self = FLUTTER_WIREGUARD_WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_parent_class)->dispose(object);
}

static void flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_init(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self) {
}

static void flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_class_init(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_dispose;
}

static FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_new(FlValue* response) {
  FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self = FLUTTER_WIREGUARD_WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE(g_object_new(flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_is_error(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_code(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE(self), nullptr);
  g_assert(flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_message(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE(self), nullptr);
  g_assert(flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_details(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* self) {
  g_return_val_if_fail(FLUTTER_WIREGUARD_IS_WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE(self), nullptr);
  g_assert(flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

static void flutter_wireguard_wireguard_flutter_api_on_tunnel_status_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  GTask* task = G_TASK(user_data);
  g_task_return_pointer(task, result, g_object_unref);
}

void flutter_wireguard_wireguard_flutter_api_on_tunnel_status(FlutterWireguardWireguardFlutterApi* self, FlutterWireguardTunnelStatus* status, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_custom_object(131, G_OBJECT(status)));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_wireguard.WireguardFlutterApi.onTunnelStatus%s", self->suffix);
  g_autoptr(FlutterWireguardMessageCodec) codec = flutter_wireguard_message_codec_new();
  FlBasicMessageChannel* channel = fl_basic_message_channel_new(self->messenger, channel_name, FL_MESSAGE_CODEC(codec));
  GTask* task = g_task_new(self, cancellable, callback, user_data);
  g_task_set_task_data(task, channel, g_object_unref);
  fl_basic_message_channel_send(channel, args, cancellable, flutter_wireguard_wireguard_flutter_api_on_tunnel_status_cb, task);
}

FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_finish(FlutterWireguardWireguardFlutterApi* self, GAsyncResult* result, GError** error) {
  g_autoptr(GTask) task = G_TASK(result);
  GAsyncResult* r = G_ASYNC_RESULT(g_task_propagate_pointer(task, nullptr));
  FlBasicMessageChannel* channel = FL_BASIC_MESSAGE_CHANNEL(g_task_get_task_data(task));
  g_autoptr(FlValue) response = fl_basic_message_channel_send_finish(channel, r, error);
  if (response == nullptr) { 
    return nullptr;
  }
  return flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_new(response);
}
