// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FlutterWireguardTunnelState:
 * FLUTTER_WIREGUARD_TUNNEL_STATE_DOWN:
 * FLUTTER_WIREGUARD_TUNNEL_STATE_TOGGLE:
 * FLUTTER_WIREGUARD_TUNNEL_STATE_UP:
 *
 * Tunnel runtime state. Mirrors com.wireguard.android.backend.Tunnel.State.
 */
typedef enum {
  FLUTTER_WIREGUARD_TUNNEL_STATE_DOWN = 0,
  FLUTTER_WIREGUARD_TUNNEL_STATE_TOGGLE = 1,
  FLUTTER_WIREGUARD_TUNNEL_STATE_UP = 2
} FlutterWireguardTunnelState;

/**
 * FlutterWireguardBackendKind:
 * FLUTTER_WIREGUARD_BACKEND_KIND_KERNEL:
 * Linux kernel WireGuard module (via wg-quick).
 * FLUTTER_WIREGUARD_BACKEND_KIND_USERSPACE:
 * Userspace implementation: wireguard-go on Android, or
 * wireguard-go / boringtun on Linux (via wg-quick env var).
 * FLUTTER_WIREGUARD_BACKEND_KIND_UNKNOWN:
 * Backend not initialised yet (or unavailable).
 *
 * Identifies which underlying engine is in use.
 */
typedef enum {
  FLUTTER_WIREGUARD_BACKEND_KIND_KERNEL = 0,
  FLUTTER_WIREGUARD_BACKEND_KIND_USERSPACE = 1,
  FLUTTER_WIREGUARD_BACKEND_KIND_UNKNOWN = 2
} FlutterWireguardBackendKind;

/**
 * FlutterWireguardTunnelStatus:
 *
 * A snapshot of a tunnel's runtime status.
 */

G_DECLARE_FINAL_TYPE(FlutterWireguardTunnelStatus, flutter_wireguard_tunnel_status, FLUTTER_WIREGUARD, TUNNEL_STATUS, GObject)

/**
 * flutter_wireguard_tunnel_status_new:
 * name: field in this object.
 * state: field in this object.
 * rx: field in this object.
 * tx: field in this object.
 * handshake: field in this object.
 *
 * Creates a new #TunnelStatus object.
 *
 * Returns: a new #FlutterWireguardTunnelStatus
 */
FlutterWireguardTunnelStatus* flutter_wireguard_tunnel_status_new(const gchar* name, FlutterWireguardTunnelState state, int64_t rx, int64_t tx, int64_t handshake);

/**
 * flutter_wireguard_tunnel_status_get_name
 * @object: a #FlutterWireguardTunnelStatus.
 *
 * Tunnel/interface name (e.g. "wg0").
 *
 * Returns: the field value.
 */
const gchar* flutter_wireguard_tunnel_status_get_name(FlutterWireguardTunnelStatus* object);

/**
 * flutter_wireguard_tunnel_status_get_state
 * @object: a #FlutterWireguardTunnelStatus.
 *
 * Current state.
 *
 * Returns: the field value.
 */
FlutterWireguardTunnelState flutter_wireguard_tunnel_status_get_state(FlutterWireguardTunnelStatus* object);

/**
 * flutter_wireguard_tunnel_status_get_rx
 * @object: a #FlutterWireguardTunnelStatus.
 *
 * Total bytes received across all peers.
 *
 * Returns: the field value.
 */
int64_t flutter_wireguard_tunnel_status_get_rx(FlutterWireguardTunnelStatus* object);

/**
 * flutter_wireguard_tunnel_status_get_tx
 * @object: a #FlutterWireguardTunnelStatus.
 *
 * Total bytes transmitted across all peers.
 *
 * Returns: the field value.
 */
int64_t flutter_wireguard_tunnel_status_get_tx(FlutterWireguardTunnelStatus* object);

/**
 * flutter_wireguard_tunnel_status_get_handshake
 * @object: a #FlutterWireguardTunnelStatus.
 *
 * Latest handshake epoch milliseconds (0 if none yet).
 *
 * Returns: the field value.
 */
int64_t flutter_wireguard_tunnel_status_get_handshake(FlutterWireguardTunnelStatus* object);

/**
 * FlutterWireguardBackendInfo:
 *
 */

G_DECLARE_FINAL_TYPE(FlutterWireguardBackendInfo, flutter_wireguard_backend_info, FLUTTER_WIREGUARD, BACKEND_INFO, GObject)

/**
 * flutter_wireguard_backend_info_new:
 * kind: field in this object.
 * detail: field in this object.
 *
 * Creates a new #BackendInfo object.
 *
 * Returns: a new #FlutterWireguardBackendInfo
 */
FlutterWireguardBackendInfo* flutter_wireguard_backend_info_new(FlutterWireguardBackendKind kind, const gchar* detail);

/**
 * flutter_wireguard_backend_info_get_kind
 * @object: a #FlutterWireguardBackendInfo.
 *
 * Gets the value of the kind field of @object.
 *
 * Returns: the field value.
 */
FlutterWireguardBackendKind flutter_wireguard_backend_info_get_kind(FlutterWireguardBackendInfo* object);

/**
 * flutter_wireguard_backend_info_get_detail
 * @object: a #FlutterWireguardBackendInfo.
 *
 * Free-form description (e.g. "GoBackend", "WgQuickBackend (kernel)",
 * "wg-quick + wireguard-go").
 *
 * Returns: the field value.
 */
const gchar* flutter_wireguard_backend_info_get_detail(FlutterWireguardBackendInfo* object);

G_DECLARE_FINAL_TYPE(FlutterWireguardMessageCodec, flutter_wireguard_message_codec, FLUTTER_WIREGUARD, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApi, flutter_wireguard_wireguard_host_api, FLUTTER_WIREGUARD, WIREGUARD_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardHostApiResponseHandle, flutter_wireguard_wireguard_host_api_response_handle, FLUTTER_WIREGUARD, WIREGUARD_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * FlutterWireguardWireguardHostApiVTable:
 *
 * Table of functions exposed by WireguardHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*start)(const gchar* name, const gchar* config, FlutterWireguardWireguardHostApiResponseHandle* response_handle, gpointer user_data);
  void (*stop)(const gchar* name, FlutterWireguardWireguardHostApiResponseHandle* response_handle, gpointer user_data);
  void (*status)(const gchar* name, FlutterWireguardWireguardHostApiResponseHandle* response_handle, gpointer user_data);
  void (*tunnel_names)(FlutterWireguardWireguardHostApiResponseHandle* response_handle, gpointer user_data);
  void (*backend)(FlutterWireguardWireguardHostApiResponseHandle* response_handle, gpointer user_data);
} FlutterWireguardWireguardHostApiVTable;

/**
 * flutter_wireguard_wireguard_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the WireguardHostApi API.
 */
void flutter_wireguard_wireguard_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterWireguardWireguardHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * flutter_wireguard_wireguard_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the WireguardHostApi API.
 */
void flutter_wireguard_wireguard_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * flutter_wireguard_wireguard_host_api_respond_start:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 *
 * Responds to WireguardHostApi.start. 
 */
void flutter_wireguard_wireguard_host_api_respond_start(FlutterWireguardWireguardHostApiResponseHandle* response_handle);

/**
 * flutter_wireguard_wireguard_host_api_respond_error_start:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to WireguardHostApi.start. 
 */
void flutter_wireguard_wireguard_host_api_respond_error_start(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_wireguard_wireguard_host_api_respond_stop:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 *
 * Responds to WireguardHostApi.stop. 
 */
void flutter_wireguard_wireguard_host_api_respond_stop(FlutterWireguardWireguardHostApiResponseHandle* response_handle);

/**
 * flutter_wireguard_wireguard_host_api_respond_error_stop:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to WireguardHostApi.stop. 
 */
void flutter_wireguard_wireguard_host_api_respond_error_stop(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_wireguard_wireguard_host_api_respond_status:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to WireguardHostApi.status. 
 */
void flutter_wireguard_wireguard_host_api_respond_status(FlutterWireguardWireguardHostApiResponseHandle* response_handle, FlutterWireguardTunnelStatus* return_value);

/**
 * flutter_wireguard_wireguard_host_api_respond_error_status:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to WireguardHostApi.status. 
 */
void flutter_wireguard_wireguard_host_api_respond_error_status(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_wireguard_wireguard_host_api_respond_tunnel_names:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to WireguardHostApi.tunnelNames. 
 */
void flutter_wireguard_wireguard_host_api_respond_tunnel_names(FlutterWireguardWireguardHostApiResponseHandle* response_handle, FlValue* return_value);

/**
 * flutter_wireguard_wireguard_host_api_respond_error_tunnel_names:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to WireguardHostApi.tunnelNames. 
 */
void flutter_wireguard_wireguard_host_api_respond_error_tunnel_names(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_wireguard_wireguard_host_api_respond_backend:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to WireguardHostApi.backend. 
 */
void flutter_wireguard_wireguard_host_api_respond_backend(FlutterWireguardWireguardHostApiResponseHandle* response_handle, FlutterWireguardBackendInfo* return_value);

/**
 * flutter_wireguard_wireguard_host_api_respond_error_backend:
 * @response_handle: a #FlutterWireguardWireguardHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to WireguardHostApi.backend. 
 */
void flutter_wireguard_wireguard_host_api_respond_error_backend(FlutterWireguardWireguardHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse, flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response, FLUTTER_WIREGUARD, WIREGUARD_FLUTTER_API_ON_TUNNEL_STATUS_RESPONSE, GObject)

/**
 * flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_is_error:
 * @response: a #FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse.
 *
 * Checks if a response to WireguardFlutterApi.onTunnelStatus is an error.
 *
 * Returns: a %TRUE if this response is an error.
 */
gboolean flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_is_error(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* response);

/**
 * flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_code:
 * @response: a #FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse.
 *
 * Get the error code for this response.
 *
 * Returns: an error code or %NULL if not an error.
 */
const gchar* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_code(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* response);

/**
 * flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_message:
 * @response: a #FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse.
 *
 * Get the error message for this response.
 *
 * Returns: an error message.
 */
const gchar* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_message(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* response);

/**
 * flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_details:
 * @response: a #FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse.
 *
 * Get the error details for this response.
 *
 * Returns: (allow-none): an error details or %NULL.
 */
FlValue* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_response_get_error_details(FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* response);

/**
 * FlutterWireguardWireguardFlutterApi:
 *
 * Platform -> host events.
 */

G_DECLARE_FINAL_TYPE(FlutterWireguardWireguardFlutterApi, flutter_wireguard_wireguard_flutter_api, FLUTTER_WIREGUARD, WIREGUARD_FLUTTER_API, GObject)

/**
 * flutter_wireguard_wireguard_flutter_api_new:
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Creates a new object to access the WireguardFlutterApi API.
 *
 * Returns: a new #FlutterWireguardWireguardFlutterApi
 */
FlutterWireguardWireguardFlutterApi* flutter_wireguard_wireguard_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * flutter_wireguard_wireguard_flutter_api_on_tunnel_status:
 * @api: a #FlutterWireguardWireguardFlutterApi.
 * @status: parameter for this method.
 * @cancellable: (allow-none): a #GCancellable or %NULL.
 * @callback: (scope async): (allow-none): a #GAsyncReadyCallback to call when the call is complete or %NULL to ignore the response.
 * @user_data: (closure): user data to pass to @callback.
 *
 * Pushed whenever a tunnel changes state or its statistics tick.
 */
void flutter_wireguard_wireguard_flutter_api_on_tunnel_status(FlutterWireguardWireguardFlutterApi* api, FlutterWireguardTunnelStatus* status, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);

/**
 * flutter_wireguard_wireguard_flutter_api_on_tunnel_status_finish:
 * @api: a #FlutterWireguardWireguardFlutterApi.
 * @result: a #GAsyncResult.
 * @error: (allow-none): #GError location to store the error occurring, or %NULL to ignore.
 *
 * Completes a flutter_wireguard_wireguard_flutter_api_on_tunnel_status() call.
 *
 * Returns: a #FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse or %NULL on error.
 */
FlutterWireguardWireguardFlutterApiOnTunnelStatusResponse* flutter_wireguard_wireguard_flutter_api_on_tunnel_status_finish(FlutterWireguardWireguardFlutterApi* api, GAsyncResult* result, GError** error);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
